<h1>Liste des hôtels</h1>
<div class="table-responsive">
<table class="table">
    <thead>
        <tr>
            <th>Nom</th>
            <th>Catégorie</th>
            <th>phone</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
<?php   foreach ($entities as $_) :?>
        <tr>
            <td><?= $_['name'];?></td>
            <td><?= $_['category'];?></td>
            <td><?= $_['phone'];?></td>
            <td><a href="<?php echo $this->url('crud', ['action' => 'get', 'entity' => 'hotel', 'id' => $_['id']]);?>">Voir</a><span>&nbsp;</span><a href="<?php echo $this->url('crud', ['action' => 'set', 'entity' => 'hotel', 'id' => $_['id']]);?>">Modifier</a></td>
        </tr>
<?php   endforeach;?>
    </tbody>
</table>
<?php
echo $this->buttons;
?>
</div>