<?php
/**
 * Created by PhpStorm.
 * User: anis
 * Date: 09/05/14
 * Time: 02:22
 */
?>
<div class="btn-group">
    <a href="<?php echo $this->url('crud', ['action' => 'set', 'entity' => $entityName, 'id' => $entity['id']]);?>" class="btn btn-default">Modifier</a>
    <a href="<?php echo $this->url('crud', ['action' => 'get', 'entity' => $entityName, 'id' => $entity['id']]);?>" class="btn btn-default">Refresh</a>
    <a href="<?php echo $this->url('crud', ['action' => 'delete', 'entity' => $entityName, 'id' => $entity['id']]);?>" class="btn btn-default btn-danger">Supprimer</a>
    <a href="<?php echo $this->url('crud', ['action' => 'list', 'entity' => $entityName]);?>" class="btn btn-default">Retour à la liste</a>
</div>