<?php
/**
 * Created by PhpStorm.
 * User: anis
 * Date: 09/05/14
 * Time: 02:22
 */
?>
<div class="form-group">
    <div class="col-sm-9 btn-group pull-right">
        <button type="submit" class="btn btn-default">Enregistrer</button>
        <a class="btn btn-default" href="<?php echo $this->url('crud', ['action' => 'get', 'entity' => $entityName, 'id' => $entity['id']]);?>">Annuler</a>
        <a class="btn btn-default" href="<?php echo $this->url('crud', ['action' => 'list', 'entity' => $entityName]);?>">Retour à la liste</a>
    </div>
</div>