<?php
/**
 * mutate.phtml
 *
 * @date        28/04/2014
 * @file        mutate.phtml
 */
?>
<form class="form-horizontal" role="form" method="post">
    <h2>Edition de l'aéroport</h2>
    <div class="form-group">
        <label class="col-sm-3 control-label" for="<?= $form->get('name')->getAttribute('id');?>"><?= $form->get('name')->getOption('label');?></label>
        <div class="col-sm-9"><?= $this->formInput($form->get('name'));?></div>
<?php   echo $this->formElementErrors($form->get('name'));?>
    </div>
    <div class="form-group">
        <label class="col-sm-3 control-label" for="<?= $form->get('code3')->getAttribute('id');?>"><?= $form->get('code3')->getOption('label');?></label>
        <div class="col-sm-9"><?= $this->formInput($form->get('code3'));?></div>
<?php   echo $this->formElementErrors($form->get('code3'));?>
    </div>
    <div class="form-group">
        <label class="col-sm-3 control-label" for="<?= $form->get('city')->getAttribute('id');?>"><?= $form->get('city')->getOption('label');?></label>
        <div class="col-sm-9"><?= $this->formSelect($form->get('city'));?></div>
<?php   echo $this->formElementErrors($form->get('city'));?>
    </div>
<?php
    echo $this->buttonsSet;
?>
</form>
